### ISSUE TITLE
Restarting to default

### ISSUE THREAD

**Issue by NikolaS1411** [holtiwilan/OfficialHackerIssuesWiki#5]
**Describe the bug**
After working sometime settings goes to default, I found out that last times this thing happened after device working for like 90min without turning off

**To Reproduce**
Everything works properly until it suddenly reset to default settings, one time also it happend after it is out of batery

**Expected behavior**
I expected device will work with my settings until it is powered on

**Screenshots**
Looking like new opened updated version, because of restart problem so i think screenshot is not meaning so much

**Firmware Version**
- Version 3.0

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S23
 - OS: Android One UI 6.0
 - Browser: Google Chrome
 - Version 
**Additional context**

**Comment by holtiwilan** [comment]
Changing #define WORDS_ADDR to 2000 might help.
Is in 3.1 and out for testing in the Facebook group

**Comment by holtiwilan** [comment]
Is in 3.1 and out for testing in the Facebook group
